Faasm-side mplementation of MPI_Sendrecv
faasm/faasm pull request #377
Opened 2020-12-09 11:32 UTC by csegarragonz

In this PR I include the `faasm`-side implementation of `MPI_Sendrecv`. The actual implementation was merged upstream to `faabric` in faasm/faabric#27 and patched in faasm/faabric#27. Check those PRs for the actual implementation details.

Additionally, I also include a feature test for a ring-like shift operation.

PS: this PR is blocked by faasm/faabric#37, once that's merged in we'll also have to update

2020-12-21 09:25 UTC, csegarragonz commented on cmake/ExternalProjects.cmake
> +    GIT_TAG "origin/link-libraries"
Will need to update this tag when faasm/faabric#47 is merged.

2021-01-04 06:02 UTC, csegarragonz commented
Tests fail with:
```
/build/faasm/bin/codegen_shared_obj: error while loading shared libraries: libpistache.so.0: cannot open shared object file: No such file or directory
```

I can reproduce this locally, but workaround it by running `sudo ldconfig`. Related with #382

2021-01-06 11:37 UTC, csegarragonz commented on .github/workflows/tests.yml
> +      - name: "Build the targets to update compile commands and dependencies"
`clang-tidy` is requiring an increasing amount of compilation targets. In particular, in this PR I encountered:
* `clang-tidy` requiring protobuf's `*.pb.*` compiled files.
* `clang-tidy` requiring `pistache` headers installed with `faabric`.

As one could expect this to be a recurring issue, and given that we are already building the targets in a, concurrent, build, we decided offline to build the `dev.tools` target in the `formatting` workflow as well.

2021-01-07 06:05 UTC, Shillaker requested changes
> Additionally, the new HTTP interface makes the test in tests/test/upload/test_upload.cpp fail to compile with the unresolved OpenSSL symbol error @Shillaker encountered before. I've commented the test out.

Are you sure this is definitely because of the new HTTP interface, or is it just because we've removed `ssl` and `crypto` as dependencies? It might be that other things depend on them, not just Faabric and Pistache (e.g. `cpprestsdk`). Remember that the upload server just uses `cpprestsdk`, and not anything HTTP-related from Faabric, so it's actually more likely that it's related to that.

Could you try adding back `ssl` and `crypto` as linked libraries in `storage` and/ or `upload`? I'd like to avoid commented out tests if possible. As a last resort, you can add `!mayfail` as you suggested although this shouldn't be necessary. I'm changing some HTTP-related stuff in #386 which may or may not be of interest.

2021-01-07 07:42 UTC, Shillaker commented on src/upload/CMakeLists.txt
> +        cpprestsdk::cpprest
Nice :ok_hand:

2021-01-07 07:43 UTC, Shillaker approved these changes

2021-01-07 07:59 UTC, merged